# Generated by Django 3.2.5 on 2021-07-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyaccount',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
