# Generated by Django 3.2.5 on 2021-07-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('maapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlainOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_operation_date', models.DateField(verbose_name='дата первой транзакции')),
                ('operation_summ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('comment', models.TextField(blank=True)),
                ('period', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.category')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.header')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(verbose_name='дата')),
                ('operation_summ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма')),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('past', models.BooleanField(default=False)),
                ('transfer_id', models.CharField(blank=True, max_length=8, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='maapp.moneyaccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.category')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.header')),
                ('plain_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='transactionapp.plainoperation')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.subcategory')),
            ],
        ),
    ]
