# Generated by Django 3.2.5 on 2021-07-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plainoperation',
            old_name='start_operation_date',
            new_name='operation_date',
        ),
    ]
