# Generated by Django 3.2.5 on 2021-07-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0002_rename_start_operation_date_plainoperation_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plainoperation',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='количество операций'),
        ),
    ]
