# Generated by Django 3.2.5 on 2021-07-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionapp', '0003_plainoperation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainoperation',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='количество операций'),
        ),
    ]
